import {
  createContext,
  ReactNode,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

export type Language = "pl" | "en";

const translations = {
  pl: {
    "nav.search": "Znajdź trasę",
    "nav.tickets": "Bilety",
    "nav.wallet": "Portfel",
    "nav.rewards": "Nagrody",
    "nav.schedule": "Grafik",
    "nav.passengerLists": "Lista pasażerów",
    "nav.roles": "Role",
    "nav.schedules": "Grafiki",
    "nav.reports": "Raporty",
    "nav.addRoute": "Dodaj trasę",
    "nav.history": "Historia",
    "nav.login": "Logowanie",
    "nav.register": "Rejestracja",
    "nav.logout": "Wyloguj",
    "nav.company": "Firma",
    "language.label": "Język",
    "home.tagline": "Tu łączą się nasze drogi!",
    "common.loading": "Ładowanie...",
    "common.error": "Błąd",
    "common.close": "Zamknij",
    "common.cancel": "Anuluj",
    "common.save": "Zapisz",
    "common.delete": "Usuń",
    "common.edit": "Edytuj",
    "common.yes": "Tak",
    "common.none": "brak",
    "auth.welcome": "Witaj w KKBus",
    "auth.loginSubtitle": "Zaloguj się, aby zarządzać rezerwacjami",
    "auth.registerSubtitle": "Zarejestruj się, aby zarządzać rezerwacjami",
    "auth.email": "Email",
    "auth.password": "Hasło",
    "auth.confirmPassword": "Powtórz hasło",
    "auth.username": "Nazwa użytkownika",
    "auth.login": "Zaloguj",
    "auth.register": "Zarejestruj",
    "auth.noAccount": "Nie masz konta?",
    "auth.hasAccount": "Masz już konto?",
    "auth.loginError": "Błąd logowania",
    "auth.loginRequestError": "Wystąpił błąd podczas logowania.",
    "auth.unknownLoginError": "Wystąpił nieznany błąd podczas logowania.",
    "auth.registrationSuccess": "Rejestracja udana. Możesz się teraz zalogować.",
    "auth.registrationError": "Błąd rejestracji. Spróbuj ponownie.",
    "auth.unknownRegistrationError": "Wystąpił nieznany błąd podczas rejestracji.",
    "auth.usernameRequired": "Nazwa użytkownika jest wymagana.",
    "auth.emailRequired": "Email jest wymagany.",
    "auth.emailInvalid": "Nieprawidłowy format email.",
    "auth.passwordRequired": "Hasło jest wymagane.",
    "auth.passwordLength": "Hasło musi mieć co najmniej 6 znaków.",
    "auth.confirmRequired": "Powtórzenie hasła jest wymagane.",
    "auth.passwordMismatch": "Hasła muszą być identyczne.",
    "auth.firstName": "Imię",
    "auth.lastName": "Nazwisko",
    "auth.birthDate": "Data urodzenia",
    "auth.phoneNumber": "Numer telefonu",
    "auth.loyaltyOptIn": "Dołącz do programu lojalnościowego",
    "auth.firstNameRequired": "Imię jest wymagane.",
    "auth.lastNameRequired": "Nazwisko jest wymagane.",
    "auth.birthDateRequired": "Data urodzenia jest wymagana.",
    "auth.phoneNumberRequired": "Numer telefonu jest wymagany.",
    "company.loading": "Ładowanie informacji...",
    "company.publicInfo": "Informacje publiczne",
    "company.description": "Firma zajmuje się transportem osób między Krakowem a Katowicami.",
    "company.contact": "Kontakt",
    "company.owner": "Właściciel",
    "company.address": "Adres",
    "company.phone": "Telefon",
    "company.fax": "Fax",
    "company.employees": "Pracownicy",
    "company.drivers": "Kierowcy",
    "company.secretariat": "Sekretariat",
    "company.vehicles": "Pojazdy",
    "company.fleetNumber": "Numer",
    "company.seats": "Miejsca",
    "company.status": "Status",
    "company.parking": "Parking",
    "vehicleStatus.ACTIVE": "Aktywny",
    "vehicleStatus.IN_REPAIR": "W naprawie",
    "vehicleStatus.UNAVAILABLE": "Niedostępny",
    "search.title": "Zarezerwuj miejsce w autobusie",
    "search.origin": "Miasto wyjazdu",
    "search.destination": "Miasto przyjazdu",
    "search.selectCity": "-- Wybierz miasto --",
    "search.search": "Szukaj tras",
    "search.searching": "Szukam tras...",
    "search.loading": "Ładowanie tras...",
    "search.available": "Dostępne trasy",
    "search.empty": "Brak dostępnych tras dla wybranego połączenia.",
    "search.selectBoth": "Wybierz miasto wyjazdu i przyjazdu.",
    "search.sameCity": "Miasto wyjazdu i przyjazdu nie mogą być takie same.",
    "search.loadError": "Błąd przy pobieraniu tras. Spróbuj ponownie.",
    "route.weekly": "kurs tygodniowy",
    "route.departure": "Odjazd",
    "route.arrival": "Przyjazd",
    "route.price": "Cena",
    "route.stops": "Przystanki pośrednie",
    "route.boardingStop": "Wsiadasz",
    "route.alightingStop": "Wysiadasz",
    "route.discountType": "Ulga",
    "route.discountNone": "Normalny",
    "route.discountStudent": "Uczeń/student -30%",
    "route.discountChild": "Dziecko do lat 5",
    "route.seats": "Liczba miejsc",
    "route.availableSeats": "Wolne miejsca: {seats}",
    "route.noSeats": "Brak wolnych miejsc",
    "route.tooManySeats": "Wybrano więcej miejsc niż jest dostępne.",
    "route.useDiscount": "Użyj 50 pkt (-10 PLN)",
    "route.removeDiscount": "Usuń zniżkę",
    "route.loadingPoints": "Pobieranie punktów...",
    "route.availablePoints": "Dostępne punkty: {points}",
    "route.finished": "Kurs zakończony",
    "route.booking": "Rezerwuję...",
    "route.book": "Zarezerwuj",
    "route.pastError": "Nie można zarezerwować zakończonego kursu.",
    "route.loginRequired": "Musisz być zalogowany, aby zarezerwować trasę!",
    "route.bookingError": "Błąd podczas tworzenia rezerwacji.",
    "route.bookingSuccess": "Rezerwacja dodana! Zdobyto {points} pkt.",
    "route.discountUsed": " Użyto {points} pkt i obniżono cenę o {amount} PLN.",
    "tickets.title": "Twoje bilety KKBus",
    "tickets.subtitle": "Zarządzaj swoimi aktywnymi i archiwalnymi przejazdami",
    "tickets.loading": "Ładowanie rezerwacji...",
    "tickets.empty": "Nie masz żadnych rezerwacji.",
    "tickets.loadError": "Nie udało się pobrać rezerwacji.",
    "tickets.cancelSuccess": "Rezerwacja została anulowana, a środki zwrócone do portfela.",
    "tickets.cancelError": "Nie udało się anulować rezerwacji.",
    "tickets.date": "Data i godzina",
    "tickets.seats": "Liczba miejsc",
    "tickets.total": "Suma do zapłaty",
    "tickets.cancel": "Anuluj rezerwację",
    "tickets.cancelling": "Anulowanie...",
    "tickets.cancelTitle": "Anuluj rezerwację (możliwe do 24h przed odjazdem)",
    "tickets.statusPurchased": "ZAKUPIONY",
    "tickets.statusCompleted": "UKOŃCZONY",
    "wallet.title": "Twój portfel KKBus",
    "wallet.balance": "Dostępne środki",
    "wallet.loyalty": "Program lojalnościowy",
    "wallet.topUp": "Zasilenie konta",
    "wallet.loading": "Ładowanie danych...",
    "wallet.loadError": "Błąd podczas pobierania danych portfela",
    "wallet.amount": "Kwota doładowania (PLN)",
    "wallet.method": "Wybierz metodę płatności",
    "wallet.card": "Karta płatnicza",
    "wallet.transfer": "Przelew",
    "wallet.submit": "Doładuj konto portfela",
    "wallet.processing": "Przetwarzanie...",
    "wallet.invalidAmount": "Wprowadź poprawną kwotę doładowania.",
    "wallet.success": "Doładowano {amount} PLN metodą {method}",
    "wallet.error": "Wystąpił błąd podczas przetwarzania wpłaty.",
    "loyalty.title": "Program lojalnościowy",
    "loyalty.subtitle": "Za zakup biletu otrzymujesz 1 punkt za każde wydane 10 PLN.",
    "loyalty.points": "Twoje punkty",
    "loyalty.catalog": "Katalog nagród",
    "loyalty.owned": "Twoje odebrane nagrody",
    "loyalty.empty": "Nie masz jeszcze odebranych nagród.",
    "loyalty.loading": "Ładowanie programu lojalnościowego...",
    "loyalty.loadError": "Nie udało się pobrać danych programu lojalnościowego.",
    "loyalty.redeem": "Odbierz",
    "loyalty.redeeming": "Odbieranie...",
    "loyalty.notEnough": "Za mało punktów",
    "loyalty.redeemed": "Odebrano: {name}",
    "loyalty.redeemError": "Nie udało się odebrać nagrody.",
    "reports.panel": "Panel sekretarki",
    "reports.title": "Raport sprzedaży biletów",
    "reports.subtitle": "Raport obejmuje kursy odjeżdżające w wybranym okresie.",
    "reports.type": "Typ raportu",
    "reports.referenceDate": "Data odniesienia",
    "reports.driver": "Kierowca",
    "reports.allDrivers": "Wszyscy kierowcy",
    "reports.vehicle": "Pojazd",
    "reports.allVehicles": "Wszystkie pojazdy",
    "reports.generate": "Generuj podgląd",
    "reports.generating": "Generowanie...",
    "reports.generated": "Wygenerowano",
    "reports.print": "Drukuj / zapisz PDF",
    "reports.courses": "Kursy",
    "reports.soldTickets": "Sprzedane bilety",
    "reports.passengers": "Pasażerowie",
    "reports.revenue": "Przychód",
    "reports.fuel": "Koszt paliwa",
    "reports.result": "Wynik",
    "reports.tickets": "Bilety",
    "reports.segment": "Odcinek",
    "reports.passengerCount": "Liczba pasażerów",
    "reports.empty": "Brak kursów spełniających wybrane kryteria.",
    "reports.placeholder": "Wybierz kryteria i wygeneruj podgląd raportu.",
    "reports.optionsError": "Nie udało się pobrać filtrów raportu.",
    "reports.generateError": "Nie udało się wygenerować raportu.",
    "reports.daily": "Dzienny",
    "reports.weekly": "Tygodniowy",
    "reports.monthly": "Miesięczny",
    "reports.yearly": "Roczny",
    "driverPassengers.panel": "Panel kierowcy",
    "driverPassengers.title": "Lista pasażerów",
    "driverPassengers.subtitle": "Kursy: {courses}, pasażerowie: {passengers}",
    "driverPassengers.loading": "Ładowanie listy pasażerów...",
    "driverPassengers.empty": "Brak rezerwacji dla Twoich kursów.",
    "driverPassengers.loadError": "Nie udało się pobrać listy pasażerów.",
    "driverPassengers.print": "Drukuj listę",
    "driverPassengers.bus": "Autobus",
    "driverPassengers.seatsSummary": "Miejsca: {reserved}/{total}",
    "driverPassengers.passenger": "Pasażer",
    "driverPassengers.contact": "Kontakt",
    "driverPassengers.segment": "Odcinek",
    "driverPassengers.seats": "Miejsca",
    "driverPassengers.discount": "Ulga",
    "routeCreate.section": "Zarządzanie trasami",
    "routeCreate.title": "Dodaj nową trasę",
    "routeCreate.editTitle": "Edytuj trasę",
    "routeCreate.subtitle": "Podany termin będzie pierwszym kursem serii powtarzanej co tydzień.",
    "routeCreate.origin": "Miasto wyjazdu",
    "routeCreate.destination": "Miasto przyjazdu",
    "routeCreate.stops": "Przystanki pośrednie",
    "routeCreate.stopsHint": "Dodaj miasta pomiędzy wyjazdem a przyjazdem w kolejności przejazdu.",
    "routeCreate.addStop": "Dodaj przystanek",
    "routeCreate.stop": "Przystanek {number}",
    "routeCreate.stopPlaceholder": "Nazwa miasta lub przystanku",
    "routeCreate.removeStop": "Usuń",
    "routeCreate.noStops": "Brak przystanków pośrednich dla tej trasy.",
    "routeCreate.departure": "Odjazd",
    "routeCreate.arrival": "Przyjazd",
    "routeCreate.driver": "Kierowca",
    "routeCreate.selectDriver": "-- Wybierz kierowcę --",
    "routeCreate.bus": "Numer pojazdu",
    "routeCreate.fuel": "Koszt paliwa",
    "routeCreate.price": "Cena",
    "routeCreate.add": "Dodaj trasę",
    "routeCreate.adding": "Dodawanie...",
    "routeCreate.saving": "Zapisywanie...",
    "routeCreate.saveChanges": "Zapisz zmiany",
    "routeCreate.cancelEdit": "Anuluj edycję",
    "routeCreate.edit": "Edytuj",
    "routeCreate.existingRoutes": "Istniejące trasy",
    "routeCreate.existingRoutesHint": "Wybierz trasę z listy, aby załadować ją do formularza edycji.",
    "routeCreate.noRoutes": "Brak zapisanych tras.",
    "routeCreate.loadError": "Nie udało się pobrać danych tras.",
    "routeCreate.driversError": "Nie udało się pobrać listy kierowców.",
    "routeCreate.timeError": "Czas przyjazdu musi być późniejszy niż czas odjazdu.",
    "routeCreate.stopError": "Przystanek pośredni nie może być taki sam jak start lub cel.",
    "routeCreate.success": "Trasa została dodana.",
    "routeCreate.error": "Nie udało się dodać trasy.",
    "routeCreate.updateSuccess": "Trasa została zaktualizowana.",
    "routeCreate.updateError": "Nie udało się zaktualizować trasy.",
  },
  en: {
    "nav.search": "Find a route",
    "nav.tickets": "Tickets",
    "nav.wallet": "Wallet",
    "nav.rewards": "Rewards",
    "nav.schedule": "Schedule",
    "nav.passengerLists": "Passenger lists",
    "nav.roles": "Roles",
    "nav.schedules": "Schedules",
    "nav.reports": "Reports",
    "nav.addRoute": "Add route",
    "nav.history": "History",
    "nav.login": "Sign in",
    "nav.register": "Register",
    "nav.logout": "Sign out",
    "nav.company": "Company",
    "language.label": "Language",
    "home.tagline": "Where our roads meet!",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.close": "Close",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.yes": "Yes",
    "common.none": "none",
    "auth.welcome": "Welcome to KKBus",
    "auth.loginSubtitle": "Sign in to manage your reservations",
    "auth.registerSubtitle": "Register to manage your reservations",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm password",
    "auth.username": "Username",
    "auth.login": "Sign in",
    "auth.register": "Register",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.loginError": "Sign-in error",
    "auth.loginRequestError": "An error occurred while signing in.",
    "auth.unknownLoginError": "An unknown sign-in error occurred.",
    "auth.registrationSuccess": "Registration successful. You can now sign in.",
    "auth.registrationError": "Registration failed. Please try again.",
    "auth.unknownRegistrationError": "An unknown registration error occurred.",
    "auth.usernameRequired": "Username is required.",
    "auth.emailRequired": "Email is required.",
    "auth.emailInvalid": "Invalid email format.",
    "auth.passwordRequired": "Password is required.",
    "auth.passwordLength": "Password must contain at least 6 characters.",
    "auth.confirmRequired": "Password confirmation is required.",
    "auth.passwordMismatch": "Passwords must match.",
    "auth.firstName": "First name",
    "auth.lastName": "Last name",
    "auth.birthDate": "Date of birth",
    "auth.phoneNumber": "Phone number",
    "auth.loyaltyOptIn": "Join the loyalty program",
    "auth.firstNameRequired": "First name is required.",
    "auth.lastNameRequired": "Last name is required.",
    "auth.birthDateRequired": "Date of birth is required.",
    "auth.phoneNumberRequired": "Phone number is required.",
    "company.loading": "Loading information...",
    "company.publicInfo": "Public information",
    "company.description": "The company provides passenger transport between Krakow and Katowice.",
    "company.contact": "Contact",
    "company.owner": "Owner",
    "company.address": "Address",
    "company.phone": "Phone",
    "company.fax": "Fax",
    "company.employees": "Employees",
    "company.drivers": "Drivers",
    "company.secretariat": "Secretariat",
    "company.vehicles": "Vehicles",
    "company.fleetNumber": "Number",
    "company.seats": "Seats",
    "company.status": "Status",
    "company.parking": "Parking",
    "vehicleStatus.ACTIVE": "Active",
    "vehicleStatus.IN_REPAIR": "In repair",
    "vehicleStatus.UNAVAILABLE": "Unavailable",
    "search.title": "Reserve a bus seat",
    "search.origin": "Departure city",
    "search.destination": "Destination city",
    "search.selectCity": "-- Select a city --",
    "search.search": "Search routes",
    "search.searching": "Searching...",
    "search.loading": "Loading routes...",
    "search.available": "Available routes",
    "search.empty": "No routes are available for the selected connection.",
    "search.selectBoth": "Select both departure and destination cities.",
    "search.sameCity": "Departure and destination cities must be different.",
    "search.loadError": "Could not load routes. Please try again.",
    "route.weekly": "weekly service",
    "route.departure": "Departure",
    "route.arrival": "Arrival",
    "route.price": "Price",
    "route.stops": "Intermediate stops",
    "route.boardingStop": "Boarding stop",
    "route.alightingStop": "Alighting stop",
    "route.discountType": "Discount",
    "route.discountNone": "Regular",
    "route.discountStudent": "Student/pupil -30%",
    "route.discountChild": "Child under 5",
    "route.seats": "Number of seats",
    "route.availableSeats": "Available seats: {seats}",
    "route.noSeats": "No seats available",
    "route.tooManySeats": "More seats selected than available.",
    "route.useDiscount": "Use 50 pts (-10 PLN)",
    "route.removeDiscount": "Remove discount",
    "route.loadingPoints": "Loading points...",
    "route.availablePoints": "Available points: {points}",
    "route.finished": "Service completed",
    "route.booking": "Booking...",
    "route.book": "Book",
    "route.pastError": "A completed service cannot be booked.",
    "route.loginRequired": "You must sign in to book a route!",
    "route.bookingError": "Could not create the reservation.",
    "route.bookingSuccess": "Reservation created! You earned {points} pts.",
    "route.discountUsed": " {points} pts were used for a {amount} PLN discount.",
    "tickets.title": "Your KKBus tickets",
    "tickets.subtitle": "Manage your active and past journeys",
    "tickets.loading": "Loading reservations...",
    "tickets.empty": "You do not have any reservations.",
    "tickets.loadError": "Could not load reservations.",
    "tickets.cancelSuccess": "The reservation was cancelled and the payment was returned to your wallet.",
    "tickets.cancelError": "Could not cancel the reservation.",
    "tickets.date": "Date and time",
    "tickets.seats": "Number of seats",
    "tickets.total": "Total paid",
    "tickets.cancel": "Cancel reservation",
    "tickets.cancelling": "Cancelling...",
    "tickets.cancelTitle": "Cancel reservation (available up to 24 hours before departure)",
    "tickets.statusPurchased": "PURCHASED",
    "tickets.statusCompleted": "COMPLETED",
    "wallet.title": "Your KKBus wallet",
    "wallet.balance": "Available funds",
    "wallet.loyalty": "Loyalty program",
    "wallet.topUp": "Add funds",
    "wallet.loading": "Loading data...",
    "wallet.loadError": "Could not load wallet data",
    "wallet.amount": "Top-up amount (PLN)",
    "wallet.method": "Select payment method",
    "wallet.card": "Payment card",
    "wallet.transfer": "Bank transfer",
    "wallet.submit": "Add funds to wallet",
    "wallet.processing": "Processing...",
    "wallet.invalidAmount": "Enter a valid top-up amount.",
    "wallet.success": "Added {amount} PLN using {method}",
    "wallet.error": "An error occurred while processing the payment.",
    "loyalty.title": "Loyalty program",
    "loyalty.subtitle": "You receive 1 point for every 10 PLN spent on tickets.",
    "loyalty.points": "Your points",
    "loyalty.catalog": "Rewards catalog",
    "loyalty.owned": "Your redeemed rewards",
    "loyalty.empty": "You have not redeemed any rewards yet.",
    "loyalty.loading": "Loading loyalty program...",
    "loyalty.loadError": "Could not load loyalty program data.",
    "loyalty.redeem": "Redeem",
    "loyalty.redeeming": "Redeeming...",
    "loyalty.notEnough": "Not enough points",
    "loyalty.redeemed": "Redeemed: {name}",
    "loyalty.redeemError": "Could not redeem the reward.",
    "reports.panel": "Secretary panel",
    "reports.title": "Ticket sales report",
    "reports.subtitle": "The report includes services departing during the selected period.",
    "reports.type": "Report type",
    "reports.referenceDate": "Reference date",
    "reports.driver": "Driver",
    "reports.allDrivers": "All drivers",
    "reports.vehicle": "Vehicle",
    "reports.allVehicles": "All vehicles",
    "reports.generate": "Generate preview",
    "reports.generating": "Generating...",
    "reports.generated": "Generated",
    "reports.print": "Print / save PDF",
    "reports.courses": "Services",
    "reports.soldTickets": "Tickets sold",
    "reports.passengers": "Passengers",
    "reports.revenue": "Revenue",
    "reports.fuel": "Fuel cost",
    "reports.result": "Result",
    "reports.tickets": "Tickets",
    "reports.segment": "Segment",
    "reports.passengerCount": "Passenger count",
    "reports.empty": "No services match the selected criteria.",
    "reports.placeholder": "Select criteria and generate a report preview.",
    "reports.optionsError": "Could not load report filters.",
    "reports.generateError": "Could not generate the report.",
    "reports.daily": "Daily",
    "reports.weekly": "Weekly",
    "reports.monthly": "Monthly",
    "reports.yearly": "Yearly",
    "driverPassengers.panel": "Driver panel",
    "driverPassengers.title": "Passenger list",
    "driverPassengers.subtitle": "Services: {courses}, passengers: {passengers}",
    "driverPassengers.loading": "Loading passenger lists...",
    "driverPassengers.empty": "No reservations for your services.",
    "driverPassengers.loadError": "Could not load passenger lists.",
    "driverPassengers.print": "Print list",
    "driverPassengers.bus": "Bus",
    "driverPassengers.seatsSummary": "Seats: {reserved}/{total}",
    "driverPassengers.passenger": "Passenger",
    "driverPassengers.contact": "Contact",
    "driverPassengers.segment": "Segment",
    "driverPassengers.seats": "Seats",
    "driverPassengers.discount": "Discount",
    "routeCreate.section": "Route management",
    "routeCreate.title": "Add a new route",
    "routeCreate.editTitle": "Edit route",
    "routeCreate.subtitle": "The selected date will be the first service in a weekly series.",
    "routeCreate.origin": "Departure city",
    "routeCreate.destination": "Destination city",
    "routeCreate.stops": "Intermediate stops",
    "routeCreate.stopsHint": "Add cities between departure and destination in travel order.",
    "routeCreate.addStop": "Add stop",
    "routeCreate.stop": "Stop {number}",
    "routeCreate.stopPlaceholder": "City or stop name",
    "routeCreate.removeStop": "Remove",
    "routeCreate.noStops": "This route has no intermediate stops.",
    "routeCreate.departure": "Departure",
    "routeCreate.arrival": "Arrival",
    "routeCreate.driver": "Driver",
    "routeCreate.selectDriver": "-- Select a driver --",
    "routeCreate.bus": "Vehicle number",
    "routeCreate.fuel": "Fuel cost",
    "routeCreate.price": "Price",
    "routeCreate.add": "Add route",
    "routeCreate.adding": "Adding...",
    "routeCreate.saving": "Saving...",
    "routeCreate.saveChanges": "Save changes",
    "routeCreate.cancelEdit": "Cancel editing",
    "routeCreate.edit": "Edit",
    "routeCreate.existingRoutes": "Existing routes",
    "routeCreate.existingRoutesHint": "Select a route from the list to load it into the edit form.",
    "routeCreate.noRoutes": "No saved routes.",
    "routeCreate.loadError": "Could not load route data.",
    "routeCreate.driversError": "Could not load the driver list.",
    "routeCreate.timeError": "Arrival must be later than departure.",
    "routeCreate.stopError": "An intermediate stop cannot match the origin or destination.",
    "routeCreate.success": "The route was added.",
    "routeCreate.error": "Could not add the route.",
    "routeCreate.updateSuccess": "The route was updated.",
    "routeCreate.updateError": "Could not update the route.",
  },
} as const;

type TranslationKey = keyof typeof translations.pl;
type TranslationVariables = Record<string, string | number>;

interface LanguageContextValue {
  language: Language;
  locale: "pl-PL" | "en-GB";
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey, variables?: TranslationVariables) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() =>
    localStorage.getItem("language") === "en" ? "en" : "pl",
  );

  const setLanguage = useCallback((nextLanguage: Language) => {
    localStorage.setItem("language", nextLanguage);
    setLanguageState(nextLanguage);
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = useCallback(
    (key: TranslationKey, variables: TranslationVariables = {}) => {
      let value: string = translations[language][key];
      Object.entries(variables).forEach(([name, replacement]) => {
        value = value.replace(new RegExp(`\\{${name}\\}`, "g"), String(replacement));
      });
      return value;
    },
    [language],
  );

  const value = useMemo(
    () => ({
      language,
      locale: language === "pl" ? ("pl-PL" as const) : ("en-GB" as const),
      setLanguage,
      t,
    }),
    [language, setLanguage, t],
  );

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
};
