spring:
  flyway:
    enabled: false
  application:
    name: kkbus
  datasource:
    url: "jdbc:mysql://localhost:3306/kkbus?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: qwerty
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800
server:
  port: 8080
