spring.application.name=projekt_zespolowy
spring.config.import=optional:file:.env[.properties]
# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false